x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  oracle:
    restart: "unless-stopped"
    image: ghcr.io/smoothly-protocol/oracle:${SMOOTHLY_TAG}
    volumes:
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    ports:
      - 5040:5040/tcp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - node
      - --experimental-specifier-resolution=node
      - ./dist/index.js
      - smoothly_cli
      - -pk
      - ${ETH_PRIVATE_KEY}
      - -n
      - ${NETWORK}
      - -b
      - ${ETH_REST_URL}
      - -eth1
      - ${ETH_RPC_URL}
      - -server
