version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  oracle:
    restart: "unless-stopped"
    image: ghcr.io/smoothly-protocol/oracle:${SMOOTHLY_TAG}
    ports:
      - 5040:5040/tcp
    <<: *logging
    command:
      - smoothly_cli
      - -pk
      - ${ETH_PRIVATE_KEY}
      - -n
      - ${NETWORK}
      - -b
      - ${ETH_REST_URL}
      - -eth1
      - ${ETH_RPC_URL}
